<?php
echo "<!DOCTYPE HTML>
<html>
   <head>
      <meta charset='utf-8'>
      <title>Registration Success</title>
      <link rel='stylesheet' href='css/normalize.css'>
      <link rel='stylesheet' href='css/style.css'>
   </head>
   <body>
      <h2>REGISTRATION SUCCESS</h2>
      <h2>You have successfully registered. Click <a href='./index.php?action=login'>here</a> to go back to the home page and log in, or you can simply wait 5 seconds to be redirected.</h2>
   </body>
</html>
";
